export type Category = 'fintech' | 'ai' | 'quant' | 'web' | 'tools';

export interface Project {
  id: string;
  name: string;
  description: string;
  stat: string;
  statLabel: string;
  tags: string[];
  category: Category[];
  language: string;
  featured: boolean;
  href: string;
  githubHref: string;
  image?: string;
}

export const projects: Project[] = [
  {
    id: 'cryptoprism-db',
    name: 'CryptoPrism DB',
    description: 'Three-database GCP architecture processing 1B+ data points daily across 1,000+ coins and 130+ technical indicators. 99.9% uptime SLA.',
    stat: '1B+',
    statLabel: 'data points / day',
    tags: ['GCP', 'PostgreSQL', 'Python', 'FastAPI', 'ETL'],
    category: ['fintech', 'quant'],
    language: 'Python',
    featured: true,
    href: 'https://github.com/CryptoPrism-io',
    githubHref: 'https://github.com/CryptoPrism-io',
  },
  {
    id: 'cryptoprism-web',
    name: 'CryptoPrism Web',
    description: 'AI-powered crypto intelligence platform for independent traders. React + Firebase frontend with real-time market data, indicators and alerts.',
    stat: '1K+',
    statLabel: 'coins tracked',
    tags: ['React', 'TypeScript', 'Firebase', 'Recharts'],
    category: ['fintech', 'ai'],
    language: 'TypeScript',
    featured: true,
    href: 'https://github.com/CryptoPrism-io',
    githubHref: 'https://github.com/CryptoPrism-io',
  },
  {
    id: 'pratyaksha',
    name: 'Pratyaksha',
    description: 'Real-time crypto market scanner with 130+ technical indicators computed on the fly. Pairs with CryptoPrism DB for live analysis.',
    stat: '130+',
    statLabel: 'indicators',
    tags: ['Python', 'FastAPI', 'vectorbt', 'Redis'],
    category: ['quant', 'fintech'],
    language: 'Python',
    featured: true,
    href: 'https://github.com/yogeshsahu',
    githubHref: 'https://github.com/yogeshsahu',
  },
  {
    id: 'gyanmarg',
    name: 'Gyanmarg',
    description: 'Knowledge management platform powered by Gemini AI. Captures, connects and surfaces mental models from your learning history.',
    stat: '6',
    statLabel: 'mental models live',
    tags: ['React', 'Gemini AI', 'Firebase', 'NLP'],
    category: ['ai', 'web'],
    language: 'TypeScript',
    featured: true,
    href: 'https://github.com/yogeshsahu',
    githubHref: 'https://github.com/yogeshsahu',
  },
  {
    id: 'forex-session',
    name: 'Forex Session Dashboard',
    description: 'Real-time Forex session overlap visualizer. Identifies London/NY/Tokyo overlap windows and optimal trading windows with live spread data.',
    stat: '4',
    statLabel: 'sessions tracked',
    tags: ['React', 'Python', 'Streamlit', 'Data Viz'],
    category: ['quant', 'fintech'],
    language: 'Python',
    featured: true,
    href: 'https://github.com/yogeshsahu',
    githubHref: 'https://github.com/yogeshsahu',
  },
  {
    id: 'habit-tracker',
    name: 'Habit Tracker',
    description: 'Behavioural science-backed habit formation app. Streak tracking, Seinfeld chain visualisation, daily check-ins with push notifications.',
    stat: '50K',
    statLabel: 'downloads',
    tags: ['Unity', 'C#', 'Firebase', 'Mobile'],
    category: ['web', 'tools'],
    language: 'C#',
    featured: true,
    href: 'https://github.com/yogeshsahu',
    githubHref: 'https://github.com/yogeshsahu',
  },
  {
    id: 'timesfm-crypto',
    name: 'TimesFM × Crypto',
    description: 'Google\'s TimesFM foundation model applied to live BTC/ETH price forecasting. Dissertation research project — Strathclyde MS FinTech.',
    stat: '2',
    statLabel: 'papers cited',
    tags: ['TimesFM', 'Python', 'ML', 'FinTech'],
    category: ['quant', 'ai'],
    language: 'Python',
    featured: false,
    href: 'https://github.com/yogeshsahu',
    githubHref: 'https://github.com/yogeshsahu',
  },
  {
    id: 'algo-backtest',
    name: 'Algo Backtest Engine',
    description: 'Vectorised backtesting framework for crypto strategies. Supports multi-asset, multi-timeframe, with Monte Carlo risk simulation.',
    stat: '10+',
    statLabel: 'strategies tested',
    tags: ['Python', 'vectorbt', 'Pandas', 'NumPy'],
    category: ['quant'],
    language: 'Python',
    featured: false,
    href: 'https://github.com/yogeshsahu',
    githubHref: 'https://github.com/yogeshsahu',
  },
  {
    id: 'cryptoprism-mobile',
    name: 'CryptoPrism Mobile',
    description: 'React Native companion app for CryptoPrism. Portfolio tracker, price alerts, and AI-generated trade signals on iOS and Android.',
    stat: 'iOS + Android',
    statLabel: 'platforms',
    tags: ['React Native', 'TypeScript', 'Firebase'],
    category: ['fintech', 'ai'],
    language: 'TypeScript',
    featured: false,
    href: 'https://github.com/CryptoPrism-io',
    githubHref: 'https://github.com/CryptoPrism-io',
  },
  {
    id: 'market-sentiment',
    name: 'Market Sentiment Engine',
    description: 'NLP pipeline aggregating crypto social sentiment from Twitter, Reddit and Telegram. Real-time fear/greed index with historical overlay.',
    stat: '3',
    statLabel: 'data sources',
    tags: ['Python', 'NLP', 'BERT', 'Kafka'],
    category: ['quant', 'ai'],
    language: 'Python',
    featured: false,
    href: 'https://github.com/yogeshsahu',
    githubHref: 'https://github.com/yogeshsahu',
  },
  {
    id: 'portfolio-tracker',
    name: 'Portfolio Tracker Pro',
    description: 'Multi-exchange crypto portfolio tracker with P&L analytics, tax lot accounting and Bloomberg-style performance attribution.',
    stat: '20+',
    statLabel: 'exchanges',
    tags: ['React', 'Python', 'PostgreSQL', 'Recharts'],
    category: ['fintech', 'web'],
    language: 'TypeScript',
    featured: false,
    href: 'https://github.com/yogeshsahu',
    githubHref: 'https://github.com/yogeshsahu',
  },
  {
    id: 'gcp-pipeline',
    name: 'GCP Data Pipeline',
    description: 'Production ETL pipeline on GCP: Cloud Run workers, BigQuery storage, Pub/Sub messaging, Dataflow batch processing.',
    stat: '99.9%',
    statLabel: 'uptime',
    tags: ['GCP', 'BigQuery', 'Pub/Sub', 'Terraform'],
    category: ['tools', 'quant'],
    language: 'Python',
    featured: false,
    href: 'https://github.com/yogeshsahu',
    githubHref: 'https://github.com/yogeshsahu',
  },
  {
    id: 'kari-game',
    name: 'Kari — Mobile Game',
    description: '2D temple run-style mobile game shipped to 110 countries in 21 days. 50K+ downloads. Featured by Google Play in India.',
    stat: '110',
    statLabel: 'countries',
    tags: ['Unity', 'C#', 'Game Dev', 'Mobile'],
    category: ['tools'],
    language: 'C#',
    featured: false,
    href: 'https://github.com/yogeshsahu',
    githubHref: 'https://github.com/yogeshsahu',
  },
  {
    id: 'gamerz-nation',
    name: 'Gamerz Nation Platform',
    description: 'E-sports franchise management platform for India\'s first GeForce-certified e-sports zone. 7 game franchises, event scheduling.',
    stat: '7',
    statLabel: 'franchises',
    tags: ['React', 'Node.js', 'PostgreSQL', 'E-Sports'],
    category: ['web'],
    language: 'TypeScript',
    featured: false,
    href: 'https://github.com/yogeshsahu',
    githubHref: 'https://github.com/yogeshsahu',
  },
  {
    id: 'defi-scanner',
    name: 'DeFi Protocol Scanner',
    description: 'On-chain analytics for DeFi protocols on Ethereum and Solana. Tracks TVL, yield rates, liquidity pool flows with smart contract parsing.',
    stat: '50+',
    statLabel: 'protocols',
    tags: ['Web3', 'Python', 'Ethereum', 'Solana'],
    category: ['fintech', 'quant'],
    language: 'Python',
    featured: false,
    href: 'https://github.com/yogeshsahu',
    githubHref: 'https://github.com/yogeshsahu',
  },
  {
    id: 'options-pricer',
    name: 'Crypto Options Pricer',
    description: 'Black-Scholes and Monte Carlo options pricing engine adapted for crypto markets. Greeks calculator, vol surface visualisation.',
    stat: 'BS + MC',
    statLabel: 'models',
    tags: ['Python', 'NumPy', 'SciPy', 'Options'],
    category: ['quant'],
    language: 'Python',
    featured: false,
    href: 'https://github.com/yogeshsahu',
    githubHref: 'https://github.com/yogeshsahu',
  },
  {
    id: 'api-gateway',
    name: 'FastAPI Gateway',
    description: 'Production API gateway for CryptoPrism with JWT auth, rate limiting, Redis caching, OpenAPI documentation and Prometheus metrics.',
    stat: '<50ms',
    statLabel: 'p99 latency',
    tags: ['FastAPI', 'Redis', 'JWT', 'Docker'],
    category: ['tools'],
    language: 'Python',
    featured: false,
    href: 'https://github.com/yogeshsahu',
    githubHref: 'https://github.com/yogeshsahu',
  },
  {
    id: 'power-bi-dashboard',
    name: 'Power BI FinTech Dashboard',
    description: 'Executive-grade Power BI dashboard for fintech KPIs. DPIIT reporting metrics, investor-facing revenue and growth visualisations.',
    stat: 'PL-300',
    statLabel: 'certified',
    tags: ['Power BI', 'DAX', 'Azure', 'FinTech'],
    category: ['tools', 'fintech'],
    language: 'DAX',
    featured: false,
    href: 'https://github.com/yogeshsahu',
    githubHref: 'https://github.com/yogeshsahu',
  },
  {
    id: 'trading-journal',
    name: 'Trading Journal',
    description: 'Systematic trading journal with trade tagging, performance attribution by strategy/asset class and behavioural bias identification.',
    stat: '100+',
    statLabel: 'trade metrics',
    tags: ['React', 'SQLite', 'Python', 'Analytics'],
    category: ['tools', 'quant'],
    language: 'TypeScript',
    featured: false,
    href: 'https://github.com/yogeshsahu',
    githubHref: 'https://github.com/yogeshsahu',
  },
  {
    id: 'news-aggregator',
    name: 'FinTech News Engine',
    description: 'AI-curated financial news aggregator. NLP relevance scoring, topic clustering, breaking news alerts with sentiment tagging.',
    stat: '200+',
    statLabel: 'sources',
    tags: ['Python', 'NLP', 'FastAPI', 'React'],
    category: ['ai', 'fintech'],
    language: 'Python',
    featured: false,
    href: 'https://github.com/yogeshsahu',
    githubHref: 'https://github.com/yogeshsahu',
  },
];

export const featuredProjects = projects.filter(p => p.featured);
